수강 신청 대기열을 구현합니다.
ddwu-aws-cloud-club/team-b pull request #21
Opened 2024-04-09 16:47 UTC by yubin21

## Description ✍️
* Redis를 이용하여 대기열을 구현합니다.

## Screen Shot 📷
local 환경에서 대기열이 정상적으로 작동함을 확인했습니다.
![KakaoTalk_Photo_2024-04-10-01-45-07](https://github.com/ddwu-aws-cloud-club/team-b/assets/80163835/a5742e51-1e01-4cf7-9c96-2ac67d7ad842)

## 테스트 시 유의사항 ⚠️
* 데드락에 주의하여 테스트 부탁드립니다.

## Merge 전 체크 리스트 ✅
- [x] Backend 컨벤션을 잘 지켰나요?
- [x] 오류 없이 해당 기능이 잘 동작되나요?
- [ ] 모든 리뷰어의 승인을 받았나요?

2024-04-09 17:06 UTC, yu-heejin requested changes
몇가지 질문 사항 있어서 리뷰 드렸습니다! 고생하셨어요~~

2024-04-09 17:06 UTC, yu-heejin commented on src/main/java/org/course/registration/service/EnrollService.java
> +        Optional<Enroll> enrollment = enrollRepository.findByStudentIdAndCourseId(studentId, courseId);
Optional로 받으시고 아래와 같이 코드를 수정해도 더 좋을 것 같네요.

```
enrollRepository.findByStudentIdAndCourseId(id)
            .ifPresentOrElse(
                result -> {
                    
                },
                () -> {
                   
                }
            );
```

2024-04-09 17:06 UTC, yu-heejin commented on src/main/java/org/course/registration/service/WaitlistService.java
> +        while (currentCount < limit) {
조건이 currentCount < limit 인 이유가 있으신가요? 뭔가,, 현재 수강중인 인원은 계속 limit보다 작을수밖에 없어서 무한 루프 돌 것 같은데..!

2024-04-09 17:10 UTC, yubin21 commented on src/main/java/org/course/registration/service/EnrollService.java
> +        } else {
코드 수정하다가 잘못 들어간거 같네요 확인 감사합니다!

2024-04-09 17:12 UTC, yubin21 commented on src/main/java/org/course/registration/service/EnrollService.java
> +        waitlistService.addToWaitlist(studentId, courseId);
addToWaitlist 부분은 redis 대기열에만 추가하는 부분이고, DB에 저장하는 것은 processWaitlist 에서 진행됩니다 :)

2024-04-09 17:21 UTC, yubin21 commented on src/main/java/org/course/registration/service/WaitlistService.java
> +        while (currentCount < limit) {
해당 부분은 Scheduler 에 해당 함수를 사용하며 무한 루프를 방지하기 위해 추가했던 조건이었습니다. 대기열 구현에 있어, Scheduler를 구현하는 것에 대해서는 아직 고민이 있어 해당 조건을 남겨두었습니다👀

2024-04-11 04:35 UTC, yubin21 commented on src/main/java/org/course/registration/service/EnrollService.java
> +    public List<Course> findEnrollmentsByStudentId(String studentId) {
EnrollmentController 에서 사용하고 있어 public으로 해두었습니다🙌

2024-04-11 07:03 UTC, yubin21 commented on src/main/java/org/course/registration/service/EnrollService.java
> +        Optional<Enroll> enrollment = enrollRepository.findByStudentIdAndCourseId(studentId, courseId);
슬랙에서 전달드린대로 return 값 문제로 인해 기존 코드대로 진행하겠습니다!

2024-04-11 07:07 UTC, merged